#TRAVIS CI

language: python

python:
  - 3.7

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="experiment_planner.settings"
    - PYTHONPATH="/home/builds/jmattick/experiment_planner"
    - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py test
